### ISSUE TITLE
how to send transcation frequently?

### ISSUE THREAD

**Issue by pycharmsas** [FrankC01/pysui#105]
I used Pysui to send 10 consecutive transactions, and I recorded the sending time of each transaction and the end time of successful sending. I also calculated the time difference, and the results showed that each transaction took an average of more than 6 seconds to send. May I ask if there is any way to reduce the transaction time interval? I would like to send more frequently.
this is my code

**Comment by pycharmsas** [comment]
`for i in range(10):
        txn = SuiTransaction(gg)
        start = time.time()
        print(f'{i} {start}')
        txn.move_call(
            target="0xb24b6789e088b876afabca733bed2299fbc9e2d6369be4d1acfa17d8145454d9::router::swap_exact_input",
            arguments=[
                SuiU64(100000000),
                txn.split_coin(coin='0x0c61f2a83ffb6a1556e1a0e6a3f17746ae364a784ac2458dd8bb576a4758af19',
                               amounts=[100000000]),
                SuiU64(1),
                ObjectID('0x3f2d9f724f4a1ce5e71676448dc452be9a6243dac9c5b975a588c8c867066e92'),
            ],
            type_arguments=[
                '0x2::sui::SUI',
                '0xc85fd68ee4d49743d3f15da159a5c62714290f39c41eab769a5f6b9b22a1549d::test_eth::TEST_ETH',
            ],
        )
        tx_result = txn.execute(gas_budget='20000000')
        shij = time.time() - start
        print(f'{i} end {time.time()} use time {shij}')`
and this is output
`0 1683274643.308898
0 end 1683274650.3012302 use time 6.992330074310303
1 1683274650.728682
1 end 1683274657.153122 use time 6.424437046051025
2 1683274657.584933
2 end 1683274665.2230232 use time 7.63808798789978
3 1683274665.698584
3 end 1683274676.134675 use time 10.436088800430298
4 1683274676.913024
4 end 1683274683.1125472 use time 6.199520111083984
5 1683274683.6188202
5 end 1683274690.080172 use time 6.461349725723267
6 1683274690.787002
6 end 1683274696.2797499 use time 5.492746114730835
7 1683274696.710639
7 end 1683274702.243704 use time 5.533062934875488
8 1683274702.767651
8 end 1683274709.04296 use time 6.275305986404419
9 1683274709.472346
9 end 1683274715.966263 use time 6.493914842605591`

**Comment by FrankC01** [comment]
So, the first thing to note is that the activity of building the SuiTransaction potentially incurs a number of RPC calls to resolve and verify the parameters and arguments in the methods being used. 

So for your example there is at least 3 RPC calls (target, split_coin arg and last parameter ObjectID

As your example is mainnet and I have no mainnet coins, I will demonstrate using something from testnet or a simple contract of my own which emulates what you have.
