### ISSUE TITLE
[bug] Client.get_events doesn't work with cursor

### ISSUE THREAD

**Issue by debjit-bw** [FrankC01/pysui#137]
it requires cursor to be of type EventID which needs `event_seq: int, tx_seq: int` to init, however event cursor typically contains event_seq (int) and txDigest (str). if txDigest is provided in tx_seq it doesn't work (returns null)

**Comment by FrankC01** [comment]
Yes, this was legacy and I missed updating when they changed cursor behavior.

This will be published Monday to PyPi along with 0.30.0 changes

**Comment by FrankC01** [comment]
Actually, EventID is defined by JSON RPC API schema as:
```json
        "EventID": {
          "description": "Unique ID of a Sui Event, the ID is a combination of tx seq number and event seq number, the ID is local to this particular fullnode and will be different from other fullnode.",
          "type": "object",
          "required": [
            "eventSeq",
            "txDigest"
          ],
          "properties": {
            "eventSeq": {
              "$ref": "#/components/schemas/BigInt_for_uint64"
            },
            "txDigest": {
              "$ref": "#/components/schemas/TransactionDigest"
            }
          }
        },
```
Both being strings.

So, amongst other things, I'm changing EventID in the p0300 (still testing, haven't pushed yet):
```python
@versionchanged(
    version="0.30.0", reason="event_seq and tx_seq changed from int to string"
)
class EventID(SuiMap):
    """Event ID specifier."""

    def __init__(self, event_seq: str, tx_seq: str):
        """Initialize EventID."""
        super().__init__("eventSeq", event_seq)
        self.map["txDigest"] = tx_seq
```

**Comment by FrankC01** [comment]
@debjit-bw  - Pushed to branch p0300

**Comment by debjit-bw** [comment]
super! it's working now, thanks a lot!

**Comment by debjit-bw** [comment]
just a suggestion, maybe txHash is a better name for the variable than tx_seq?

**Comment by FrankC01** [comment]
txDigest is even better as it aligns to the spec. However; to change the name is another breaking change as it is a keyword. I can open an enhancement for a later release.

**Comment by debjit-bw** [comment]
haha yeah makes sense, txDigest surely better
