### ISSUE TITLE
[question] Why so strict dependencies?

### ISSUE THREAD

**Issue by Yolley** [FrankC01/pysui#142]
All dependencies are declared with `==` sign restricting them to a specific patch version. What is the reasoning behind that? In semantic versioning patch versions should not contain any breaking changes, also they often contain a fix for an issue introduced earlier. May be we should switch to `>=` or `~=` signs when declaring dependency versions?

**Comment by FrankC01** [comment]
Reasonable question. Mostly legacy but I will update to be more flexible.
