### ISSUE TITLE
[enhancement] importing a wallet with private key option

### ISSUE THREAD

**Issue by cyberomanov** [FrankC01/pysui#143]
now we can import wallets from only mnemonics, but not from private keys.

I think it's an important and necessarily feature which must be implemented.

thank you for your time and efforts.

**Comment by FrankC01** [comment]
We are overhauling our keys package due to limitations of the bip-utils library we use.

When we are doing that work we will incorporate this enhancement.

**Comment by FrankC01** [comment]
@cyberomanov 

Just to confirm, adding a method on SuiConfig to take a private keystring (`keyscheme | private_seed`) outside of initiating the config is desired.

**Additional Questions**
It should return a SuiAddress and...?
It should be put in the registry where you can lookup keypairs from address?

**Comment by cyberomanov** [comment]
> @cyberomanov
> 
> Just to confirm, adding a method on SuiConfig to take a private keystring (`keyscheme | private_seed`) outside of initiating the config is desired.
> 
> **Additional Questions** It should return a SuiAddress and...? It should be put in the registry where you can lookup keypairs from address?

for me, it would be great if importing from `private_key` is equal to importing from `mnemonic`. both externally and as a result.

**Comment by FrankC01** [comment]
I'm also giving the option that `prv_keys` on `user_config()` can take a dict or keystring. The dict would have 
```python
{"wallet_key": "0x.....", "scheme": SignatureScheme.ED25519}
```
