### ISSUE TITLE
Problem with Windows running 

### ISSUE THREAD

**Issue by DanteAdamss** [FrankC01/pysui#159]
I installed Pysui and all additional requirements like RUST, and i see library in log from command pip list, but when i try run something with this library I get `ModuleNotFoundError`

`ModuleNotFoundError: No module named 'pysui'`

**Comment by FrankC01** [comment]
Do you run in virtual environment?

**Comment by DanteAdamss** [comment]
No i run  it in main environment and library is installed here. Some time i have problem with Rust but after decides this problem i got  new one with `ModuleNotFoundError: No module named 'pysui'`

**Comment by FrankC01** [comment]
Also check that `pysui-fastcrypto` is in your `pip list`

What are the includes in the python source reporting the error look like?

**Comment by DanteAdamss** [comment]
I try run in venv and got same error.
My package list:


anyio              3.7.1
base58             2.1.1
canoser            0.8.2
certifi            2023.7.22
charset-normalizer 3.2.0
colorama           0.4.6
dataclasses-json   0.5.14
Deprecated         1.2.14
h11                0.14.0
h2                 4.1.0
hpack              4.0.0
httpcore           0.17.3
httpx              0.24.1
hyperframe         6.0.1
idna               3.4
loguru             0.7.0
marshmallow        3.20.1
mypy-extensions    1.0.0
packaging          23.1
pip                23.2.1
pydantic           1.10.12
pysui              0.33.0
pysui-fastcrypto   0.1.4
PyYAML             6.0.1
random-username    1.0.2
requests           2.31.0
setuptools         65.5.0
sniffio            1.3.0
typing_extensions  4.7.1
typing-inspect     0.9.0
typing-utils       0.1.0
urllib3            2.0.4
websockets         11.0.3
win32-setctime     1.1.0
wrapt              1.15.0

**Comment by DanteAdamss** [comment]
I try run in venv and got same error.
My package list:

mypy-extensions 1.0.0
packaging 23.1
pip 23.2.1
pydantic 1.10.12
pysui 0.33.0
pysui-fastcrypto 0.1.4
PyYAML 6.0.1

**Comment by FrankC01** [comment]
Can you run: `wallet --version`?

Also, this may be easier if you join the discord channel https://discord.gg/uCGYfY4Ph4
