### ISSUE TITLE
How to work with sponsor? ValueError: 0xd56...984e is not known.

### ISSUE THREAD

**Issue by MsLolita** [FrankC01/pysui#169]
Hello Frank! Thank you for the incredible Sui library; it is truly convenient and well-documented. I'm currently studying the Sui blockchain to develop my dApps on it, but I'm still having trouble figuring out how to send transactions with sponsors.

**Comment by FrankC01** [comment]
Answered on discord with reference for you circumstance:
https://pysui.readthedocs.io/en/latest/intro.html#running-with-user-configuration
