### ISSUE TITLE
How to Choose the Right Encryption Method

### ISSUE THREAD

**Issue by MuuJian** [FrankC01/pysui#178]
```
from pysui import SyncClient, SuiConfig
from pysui.sui.sui_config import SignatureScheme
from pysui.sui.sui_txn import SyncTransaction

cfg = SuiConfig.user_config(
    rpc_url= "https://fullnode.mainnet.sui.io",
    prv_keys=[{'wallet_key': '0x8bcb729d03b2063a00f1a99c48ca69ec0b3fb9a0e3c097742aa700624f7287dc', 'key_scheme': SignatureScheme.ED25519}],
)


client = SyncClient(cfg)
txn = SyncTransaction(client= client)

arg1 = 0 
arg2 = '{"p":"suirc-20","tick":"suis","op":"mint","amt":"10000"}' 

mint = txn.move_call(
    target="0xe09b37505173ae119a0ae3b1fdf9050a6b029391f9d9f10a3fff27e3f3115727::Operation::mint",
    arguments=[arg1, arg2],
    type_arguments=["u64", "0x1::string::String"]
)


txn.execute(gas_budget="100000")    
```
my wallet address is `0x0ca714cce56e12a647b394badc9ca8e079a7bbc37c5369523626563dc404e427`, but i got `0x8b918c9265da3f1913a1c5a2ff5da7d491e01ca3ffe2137989043daa214f600a`. and Is the program I wrote correct?

**Comment by FrankC01** [comment]
The value to assign to `wallet_key` should be the wallet private key (in hex) you get from whatever wallet you use.

The wallet **_address_** is different than the Sui address that is generated from hashing the private key. The result of converting  `"0x8bcb729d03b2063a00f1a99c48ca69ec0b3fb9a0e3c097742aa700624f7287dc"` to a Sui address is indeed **_"0x8b918c9265da3f1913a1c5a2ff5da7d491e01ca3ffe2137989043daa214f600a"_**

**Comment by MuuJian** [comment]
<img width="357" alt="image" src="https://github.com/FrankC01/pysui/assets/53962922/3b9065cc-3543-4f69-827a-db1fcb4e5faf"> get it from sui wallet, my another account use zklogin(gmail)

**Comment by FrankC01** [comment]
Ok, so if you did an 'Export Private Key', that is the value to use as you did.

I hope the key you put in your original note is not a valid private key as now the whole world has seen it. I advise not using it.

**Comment by MuuJian** [comment]
sure, but why cant get account `0x0ca714cce56e12a647b394badc9ca8e079a7bbc37c5369523626563dc404e427`

**Comment by FrankC01** [comment]
I see three txns for that address:
1. Split and transferred coin to itself
2. Split and make a move call
3. Transferred gas to address `0x0bbd98078b4f0cca41bd20590a8325135e5fd195465a82aea93c1e14784f55c1`

In the last txn, is that the address that the true private key conversion in `pysui` results in?
