### ISSUE TITLE
make_move_vector get CommandArgumentError { arg_idx: 0, kind: TypeMismatch } in command 0

### ISSUE THREAD

**Issue by krabat-h** [FrankC01/pysui#185]
My txer on testnet like this:

    txer = SyncTransaction(client=client, initial_sender=SuiAddress(userAddress))
    logger.debug("===============swaping===============")
    txer.move_call(
        target=getTarget(moduleObjectID, moduleName, 'swap'),
        arguments=[
            ObjectID(globalConfigID),
            ObjectID(poolObjectID),
            txer.make_move_vector(items=coins),
            SuiU64(100),
            SuiU64(90),
            ObjectID(clockObjectID),
            ObjectID(whitelistsObjectID),
        ],
        type_arguments=[usdtCoinType, usdcCoinType],
    )
    
My contract like this:

![image](https://github.com/FrankC01/pysui/assets/121561767/399f6c24-c779-4c0a-837d-b06628659b4f)

but I got error:
CommandArgumentError { arg_idx: 0, kind: TypeMismatch } in command 0

result is:

{"digest": "4B9Pr1F1gg6GnotKyNopEPzzkh92ZVXJwwNmKEHSgUEz", "rawTransaction": "AQAAAAAACwBDQjB4MTkzYWZiNmYwZDZmZDQ5MDk5NGM2MmFlNzE2NzVkMDY1MGEzZDE4NDM0Y2FjY2IwYzE4ODllNWUxMTEzM2ZiZgBDQjB4NTBlOTkwNTE3YTcwNWZlODA1OTIxNTI1MzZkY2I3MWY5MThjNTQ4ZDdhNDE3NjViOGVlN2NmN2E2MjZmZTIxMgBDQjB4NmI5NmZiMzViOTczYzRkZDgxNmM3ZGVmM2Q5ZmY1MzVhMDU3NWEwYjVlMmZkYmIzOGU3NDBkM2Q4MDE0MzczNgBDQjB4OTNjMDQ4OWY3Mjc5NmY1N2M3NDg2ZTIxYjRhYjE5NDY5NTgzMzZiMGVlNTNmZmEzZmRmNDIwY2ZhMzI5MDE2ZABDQjB4ZjQzODMyMTg4Y2RkN2M1NTlkYTJiNTViNjBlMWEzNThjODA0MzMwNDViZjUwODU4OTlkNGU3NmY0N2MwNGIzMwEBb0FJCRpa6g6BjnJDoTrc+0A4QtZwuaIIneBYUSYgaHoMAAAAAAAAAAEBAW/UkV5tjT4rptgXhwRuuUiuNv38ddrS4k8NSqokF6QWCewEAAAAAAABAAhkAAAAAAAAAAAIWgAAAAAAAAABAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGAQAAAAAAAAAAAQFg8yKgncZC76eCn80F2IaSZf3YhJN1KyVz09oMKQAmlObnDgAAAAAAAQIFAAUBAAABAQABAgABAwABBAAAPagKQfX+rhc+t5TwzSkxTIuO3zg3PHGL8O63mMgxy8wEc3dhcARzd2FwAgcms7xnvvwhQFjKeOqaJpApjXMaLUMJSF7D1AGYBjxKvAR1c2R0BFVTRFQAByazvGe+/CFAWMp46pomkCmNcxotQwlIXsPUAZgGPEq8BHVzZGMEVVNEQwAHAQUAAQYAAgAAAQcAAQgAAQkAAQoASs5RjOL2nTJPHMuKnTBs+KaRM5nFzVhCZ67JVcboOHIBDeZo3nZctCHtQPEdT00lt0sLQppgQPsuyvD2DVlTAd1u4E8BAAAAACDgtI89p51XbxhSNq8ERhVXSigjVdy7MMhm7MlrpW1yqUrOUYzi9p0yTxzLip0wbPimkTOZxc1YQmeuyVXG6Dhy6AMAAAAAAAAALTEBAAAAAAABYQBmp6sWI0+ROFCNXyqMyoRD/2OOGqX0dJwqBLg6j7ucCMmXhvzwDubtAOx0/r+dlU31xogyGvTHuhb+SrcY1z8CXhOQunGiFSrYnpwUo6DM6ov2K84u+7n77N5v2piTPt4=", "balanceChanges": [{"owner": {"AddressOwner": "0x4ace518ce2f69d324f1ccb8a9d306cf8a6913399c5cd584267aec955c6e83872"}, "coinType": "0x2::sui::SUI", "amount": "-1147136"}], "objectChanges": [{"type": "mutated", "sender": "0x4ace518ce2f69d324f1ccb8a9d306cf8a6913399c5cd584267aec955c6e83872", "owner": {"AddressOwner": "0x4ace518ce2f69d324f1ccb8a9d306cf8a6913399c5cd584267aec955c6e83872"}, "objectType": "0x2::coin::Coin<0x2::sui::SUI>", "objectId": "0x0de668de765cb421ed40f11d4f4d25b74b0b429a6040fb2ecaf0f60d595301dd", "version": "22012218", "previousVersion": "22012014", "digest": "3UarpDidhiXcFeyhnzwkLXk4i5ey7CvpNXMM6X2EFR4U"}, {"type": "mutated", "sender": "0x4ace518ce2f69d324f1ccb8a9d306cf8a6913399c5cd584267aec955c6e83872", "owner": {"Shared": {"initial_shared_version": 976870}}, "objectType": "0x3da80a41f5feae173eb794f0cd29314c8b8edf38373c718bf0eeb798c831cbcc::swap::Whitelists", "objectId": "0x60f322a09dc642efa7829fcd05d8869265fdd88493752b2573d3da0c29002694", "version": "22012218", "previousVersion": "22012014", "digest": "DFXqf5nKWm7TBKRpsY47ByMPoRxADYe4yQHyzMGpvZty"}, {"type": "mutated", "sender": "0x4ace518ce2f69d324f1ccb8a9d306cf8a6913399c5cd584267aec955c6e83872", "owner": {"Shared": {"initial_shared_version": 12}}, "objectType": "0x0868b71c0cba55bf0faf6c40df8c179c67a4d0ba0e79965b68b3d72d7dfbf666::config::GlobalConfig", "objectId": "0x6f4149091a5aea0e818e7243a13adcfb403842d670b9a2089de058512620687a", "version": "22012218", "previousVersion": "22012014", "digest": "GM4XzD6tRcsyu6yGSTdVkuBLicLVygGoy38TGkFLNkUt"}, {"type": "mutated", "sender": "0x4ace518ce2f69d324f1ccb8a9d306cf8a6913399c5cd584267aec955c6e83872", "owner": {"Shared": {"initial_shared_version": 322569}}, "objectType": "0x0868b71c0cba55bf0faf6c40df8c179c67a4d0ba0e79965b68b3d72d7dfbf666::pool::Pool<0x26b3bc67befc214058ca78ea9a2690298d731a2d4309485ec3d40198063c4abc::usdt::USDT, 0x26b3bc67befc214058ca78ea9a2690298d731a2d4309485ec3d40198063c4abc::usdc::USDC>", "objectId": "0x6fd4915e6d8d3e2ba6d81787046eb948ae36fdfc75dad2e24f0d4aaa2417a416", "version": "22012218", "previousVersion": "22012014", "digest": "2wjxPYpPCduvYWFq9cdWFAsZqj6PKTnWFMaDezAKdZuR"}], "transaction": {"data": {"sender": "0x4ace518ce2f69d324f1ccb8a9d306cf8a6913399c5cd584267aec955c6e83872", "messageVersion": "v1", "gasData": {"budget": 20000000, "owner": "0x4ace518ce2f69d324f1ccb8a9d306cf8a6913399c5cd584267aec955c6e83872", "price": 1000, "payment": [{"objectId": "0x0de668de765cb421ed40f11d4f4d25b74b0b429a6040fb2ecaf0f60d595301dd", "version": 22012014, "digest": "G8A1hbFsrnZXrtXtJdAMaYWhjKX4M7WFqouhethVMz3J"}]}, "transaction": {"kind": "ProgrammableTransaction", "transactions": [{"MakeMoveVec": [null, [{"Input": 0}, {"Input": 1}, {"Input": 2}, {"Input": 3}, {"Input": 4}]]}, {"MoveCall": {"package": "0x3da80a41f5feae173eb794f0cd29314c8b8edf38373c718bf0eeb798c831cbcc", "module": "swap", "function": "swap", "type_arguments": ["0x26b3bc67befc214058ca78ea9a2690298d731a2d4309485ec3d40198063c4abc::usdt::USDT", "0x26b3bc67befc214058ca78ea9a2690298d731a2d4309485ec3d40198063c4abc::usdc::USDC"], "arguments": [{"Input": 5}, {"Input": 6}, {"Result": 0}, {"Input": 7}, {"Input": 8}, {"Input": 9}, {"Input": 10}]}}], "inputs": [{"type": "pure", "valueType": null, "value": [66, 48, 120, 49, 57, 51, 97, 102, 98, 54, 102, 48, 100, 54, 102, 100, 52, 57, 48, 57, 57, 52, 99, 54, 50, 97, 101, 55, 49, 54, 55, 53, 100, 48, 54, 53, 48, 97, 51, 100, 49, 56, 52, 51, 52, 99, 97, 99, 99, 98, 48, 99, 49, 56, 56, 57, 101, 53, 101, 49, 49, 49, 51, 51, 102, 98, 102]}, {"type": "pure", "valueType": null, "value": [66, 48, 120, 53, 48, 101, 57, 57, 48, 53, 49, 55, 97, 55, 48, 53, 102, 101, 56, 48, 53, 57, 50, 49, 53, 50, 53, 51, 54, 100, 99, 98, 55, 49, 102, 57, 49, 56, 99, 53, 52, 56, 100, 55, 97, 52, 49, 55, 54, 53, 98, 56, 101, 101, 55, 99, 102, 55, 97, 54, 50, 54, 102, 101, 50, 49, 50]}, {"type": "pure", "valueType": null, "value": [66, 48, 120, 54, 98, 57, 54, 102, 98, 51, 53, 98, 57, 55, 51, 99, 52, 100, 100, 56, 49, 54, 99, 55, 100, 101, 102, 51, 100, 57, 102, 102, 53, 51, 53, 97, 48, 53, 55, 53, 97, 48, 98, 53, 101, 50, 102, 100, 98, 98, 51, 56, 101, 55, 52, 48, 100, 51, 100, 56, 48, 49, 52, 51, 55, 51, 54]}, {"type": "pure", "valueType": null, "value": [66, 48, 120, 57, 51, 99, 48, 52, 56, 57, 102, 55, 50, 55, 57, 54, 102, 53, 55, 99, 55, 52, 56, 54, 101, 50, 49, 98, 52, 97, 98, 49, 57, 52, 54, 57, 53, 56, 51, 51, 54, 98, 48, 101, 101, 53, 51, 102, 102, 97, 51, 102, 100, 102, 52, 50, 48, 99, 102, 97, 51, 50, 57, 48, 49, 54, 100]}, {"type": "pure", "valueType": null, "value": [66, 48, 120, 102, 52, 51, 56, 51, 50, 49, 56, 56, 99, 100, 100, 55, 99, 53, 53, 57, 100, 97, 50, 98, 53, 53, 98, 54, 48, 101, 49, 97, 51, 53, 56, 99, 56, 48, 52, 51, 51, 48, 52, 53, 98, 102, 53, 48, 56, 53, 56, 57, 57, 100, 52, 101, 55, 54, 102, 52, 55, 99, 48, 52, 98, 51, 51]}, {"type": "object", "objectType": "sharedObject", "objectId": "0x6f4149091a5aea0e818e7243a13adcfb403842d670b9a2089de058512620687a", "initialSharedVersion": "12", "mutable": true}, {"type": "object", "objectType": "sharedObject", "objectId": "0x6fd4915e6d8d3e2ba6d81787046eb948ae36fdfc75dad2e24f0d4aaa2417a416", "initialSharedVersion": "322569", "mutable": true}, {"type": "pure", "valueType": "u64", "value": "100"}, {"type": "pure", "valueType": "u64", "value": "90"}, {"type": "object", "objectType": "sharedObject", "objectId": "0x0000000000000000000000000000000000000000000000000000000000000006", "initialSharedVersion": "1", "mutable": false}, {"type": "object", "objectType": "sharedObject", "objectId": "0x60f322a09dc642efa7829fcd05d8869265fdd88493752b2573d3da0c29002694", "initialSharedVersion": "976870", "mutable": true}]}}, "txSignatures": ["AGanqxYjT5E4UI1fKozKhEP/Y44apfR0nCoEuDqPu5wIyZeG/PAO5u0A7HT+v52VTfXGiDIa9Me6Fv5KtxjXPwJeE5C6caIVKtienBSjoMzqi/Yrzi77ufvs3m/amJM+3g=="]}, "errors": [], "effects": {"status": {"status": "failure", "error": "CommandArgumentError { arg_idx: 0, kind: TypeMismatch } in command 0", "succeeded": false}, "messageVersion": "v1", "gasUsed": {"computationCost": 1000000, "nonRefundableStorageFee": 147136, "storageCost": 14713600, "storageRebate": 14566464}, "transactionDigest": "4B9Pr1F1gg6GnotKyNopEPzzkh92ZVXJwwNmKEHSgUEz", "gasObject": {"reference": {"objectId": "0x0de668de765cb421ed40f11d4f4d25b74b0b429a6040fb2ecaf0f60d595301dd", "version": 22012218, "digest": "3UarpDidhiXcFeyhnzwkLXk4i5ey7CvpNXMM6X2EFR4U"}, "owner": "0x4ace518ce2f69d324f1ccb8a9d306cf8a6913399c5cd584267aec955c6e83872"}, "modifiedAtVersions": [{"objectId": "0x0de668de765cb421ed40f11d4f4d25b74b0b429a6040fb2ecaf0f60d595301dd", "sequenceNumber": "22012014"}, {"objectId": "0x60f322a09dc642efa7829fcd05d8869265fdd88493752b2573d3da0c29002694", "sequenceNumber": "22012014"}, {"objectId": "0x6f4149091a5aea0e818e7243a13adcfb403842d670b9a2089de058512620687a", "sequenceNumber": "22012014"}, {"objectId": "0x6fd4915e6d8d3e2ba6d81787046eb948ae36fdfc75dad2e24f0d4aaa2417a416", "sequenceNumber": "22012014"}], "dependencies": ["4vc2KNnmteY1fpZtDzkr7CWLxFACHQNJ26XvNA3Q38CU", "7eNiBhHy76srFfFJrRPB3PfEqeAbKqGcmi3AYcueB2q8", "EXVZNLQ11KZ9vbhXf4U6KJdAPPTUjQrXsdDJgf5g6UNN", "J6168Unn71ngN6MvqKem4ogS26oSnzbUJWci2cnVkHzN"], "mutated": [{"reference": {"objectId": "0x0de668de765cb421ed40f11d4f4d25b74b0b429a6040fb2ecaf0f60d595301dd", "version": 22012218, "digest": "3UarpDidhiXcFeyhnzwkLXk4i5ey7CvpNXMM6X2EFR4U"}, "owner": "0x4ace518ce2f69d324f1ccb8a9d306cf8a6913399c5cd584267aec955c6e83872"}, {"reference": {"objectId": "0x60f322a09dc642efa7829fcd05d8869265fdd88493752b2573d3da0c29002694", "version": 22012218, "digest": "DFXqf5nKWm7TBKRpsY47ByMPoRxADYe4yQHyzMGpvZty"}, "owner": {"initial_shared_version": 976870}}, {"reference": {"objectId": "0x6f4149091a5aea0e818e7243a13adcfb403842d670b9a2089de058512620687a", "version": 22012218, "digest": "GM4XzD6tRcsyu6yGSTdVkuBLicLVygGoy38TGkFLNkUt"}, "owner": {"initial_shared_version": 12}}, {"reference": {"objectId": "0x6fd4915e6d8d3e2ba6d81787046eb948ae36fdfc75dad2e24f0d4aaa2417a416", "version": 22012218, "digest": "2wjxPYpPCduvYWFq9cdWFAsZqj6PKTnWFMaDezAKdZuR"}, "owner": {"initial_shared_version": 322569}}], "created": [], "deleted": [], "wrapped": [], "unwrapped": [], "unwrappedThenDeleted": [], "sharedObjects": [{"objectId": "0x60f322a09dc642efa7829fcd05d8869265fdd88493752b2573d3da0c29002694", "version": 22012014, "digest": "6opdSNpkpjXJXYem6MVHkagLpxpad2pC72fDGW7pHcxC"}, {"objectId": "0x6f4149091a5aea0e818e7243a13adcfb403842d670b9a2089de058512620687a", "version": 22012014, "digest": "2XGDbMpk4K47nZ39NL8cNXwy5yErM8JtAjaZVhApQpNW"}, {"objectId": "0x6fd4915e6d8d3e2ba6d81787046eb948ae36fdfc75dad2e24f0d4aaa2417a416", "version": 22012014, "digest": "A8DBCpaNhYkAP4wPbt239PzCVJ1vZsyCnQKeMysP7Gd5"}, {"objectId": "0x0000000000000000000000000000000000000000000000000000000000000006", "version": 22012217, "digest": "ANCDrnoH9GrAfQCfgSt2aK4iSdhpeGJm8psFqQiP45WU"}], "executedEpoch": 257, "eventsDigest": "0"}, "events": [], "checkpoint": "", "confirmedLocalExecution": true, "timestampMs": 0}

**Comment by FrankC01** [comment]
The first command is `make_move_vector` and you should include it's Type string:
```python
txer.make_move_vec(items=coins,item_type="0x2::coin::Coin<CoinTypeA>") # Where the type is whatever CoinTypeA is...
```

**Comment by krabat-h** [comment]
> The first command is `make_move_vector` and you should include it's Type string:
> 
> ```python
> txer.make_move_vec(items=coins,item_type="0x2::coin::Coin<CoinTypeA>") # Where the type is whatever CoinTypeA is...
> ```

I change it to this:
![image](https://github.com/FrankC01/pysui/assets/121561767/bf076623-67a3-46b3-a1b6-0ddb6c1e720c)


but it's still wrong: https://suiexplorer.com/txblock/4yLzBSAoeajuW8oQdE22GG91g7wVnaZSxedWu2fydSgS?network=testnet

![image](https://github.com/FrankC01/pysui/assets/121561767/3b075d9e-79a1-4f06-8dae-406fc51c885d)


I have another question, how to get current sui clock timestamp by pysui? I want to pass it u64 to move contract to make sure current time of transaction is not too late. 

Thanks a lot.

**Comment by FrankC01** [comment]
Here is example of make_move_vec where I also specify the type to satisfy the type in the move function:
```python
def test_tb_tracker_objvec(client: SyncClient = None):
    """."""
    client = client if client else SyncClient(SuiConfig.default_config())
    txer = SyncTransaction(client=client)
    mvec = txer.make_move_vector(
        items=[
            ObjectID(
                "0x3f473fb011c6f8cedb3eba4f6a6b0adc86286cd22a3d3fb56b0e630c58c665bb"
            ),
            ObjectID(
                "0x56b65b79b00df3b208dd929c2d82f43f1b82efc6d0b9950bcd1d5f87f0cd4b35"
            ),
        ],
        item_type="0xbefe924c0a79122e066b7aa4b376207ded7c980e23c701a53d3952074ba85576::base::Tracker",
    )
    mvecr = txer.move_call(
        target="0xbefe924c0a79122e066b7aa4b376207ded7c980e23c701a53d3952074ba85576::base::check_obj_vec",
        arguments=[mvec],
    )
```

If you can show me the equivalent in the way you structure the `make_move_vec` along with the actual values for `items=[..]` and `items_type="..."` I may have better insight

**Comment by krabat-h** [comment]
@FrankC01 here is my contract function:
![image](https://github.com/FrankC01/pysui/assets/121561767/8aa9c9e7-b728-4407-92e8-11a6caaec179)


here is my txer:
![image](https://github.com/FrankC01/pysui/assets/121561767/4e7948e5-4803-41b4-9b58-deb407587404)

here is the items(coins):

![image](https://github.com/FrankC01/pysui/assets/121561767/7f7cd6d8-b5fc-4d5f-8d01-a2d09fb9fffd)

here is the coin types:
![image](https://github.com/FrankC01/pysui/assets/121561767/b13a3f0f-e096-43ec-aa83-ae5f9a96b355)


the tx execution result is `CommandArgumentError { arg_idx: 0, kind: TypeMismatch } in command 0` :https://suiexplorer.com/txblock/BnEWsSxzPozZHCP3JmaJftsdvRgSGJjEviLEQWPB4vpi?network=testnet

the swap module is : https://suiexplorer.com/object/0x0ba65ba6a93d6b1f323e56907627856f00825962d2f799637fcbc242554c49f3?network=testnet

Thanks a lot!

**Comment by krabat-h** [comment]
things went ok when I use `txer.make_move_vector(items=coins)` without item type

**Comment by krabat-h** [comment]
> > things went ok when I use txer.make_move_vector(items=coins) without item type
> 
> Are you saying it is working now? If not... are the two 'Coins' you are putting in the vector the same type? It's hard for me to tell because you are pasting an image and not the actual source text.

It is working when I delete the item_type in make_move_vector, if I add item_type=usctcoinType, the error is CommandArgumentError { arg_idx: 0, kind: TypeMismatch } in command 0

**Comment by FrankC01** [comment]
Good to hear it is working.

What is the actual coin type string you were using in `item_type=...`?

**Comment by krabat-h** [comment]
> Good to hear it is working.
> 
> What is the actual coin type string you were using in `item_type=...`?

0x26b3bc67befc214058ca78ea9a2690298d731a2d4309485ec3d40198063c4abc::usdt::USDT
