### ISSUE TITLE
`type_tag_from` may incorrectly cut type argument.

### ISSUE THREAD

**Issue by Yolley** [FrankC01/pysui#187]
I have an object https://suiexplorer.com/object/0xb3fdbd94a1265405185715667f75a39939c4e8367270c29b8041182ccc812972?network=mainnet of type `0xb24b6789e088b876afabca733bed2299fbc9e2d6369be4d1acfa17d8145454d9::swap::LSP<0x2::sui::SUI, 0x239e9725bdab1fcb2e4798a057da809e52f13134a09bc9913659d4a80ddfdaad::shui::SHUI>`

The package through which this object was created exposes methods to interact with such objects, they require type of the object to be passed in `type_arguments`. I am trying to call `withdraw` method of the package via Pysui but it fails
https://suiexplorer.com/txblock/GaemavSfEqd7D1kb2Gd38xWoP3t6tyXVgErCakqHDCDr?network=mainnet

In transaction data I see that Pysui cut part of the type of the object `0xb24b6789e088b876afabca733bed2299fbc9e2d6369be4d1acfa17d8145454d9::swap::LSP<0x2::sui::SUI, 0x239e9725bdab1fcb2e4798a057da809e52f13134a09bc9913659d4a80ddfdaad>` which leads to `TypeArityMismatch` (as you can see, pysui cut specifically `::shui::SHUI` part at the end).

Would be it possible to fix it? These types work correctly in typescript sdk for example.

It seems that the issue originates somewhere here https://github.com/FrankC01/pysui/blob/main/pysui/sui/sui_types/bcs.py#L268

**Comment by FrankC01** [comment]
OK, will take a look later today or tomorrow. Thanks for the details.

**Comment by FrankC01** [comment]
Found the issue, when reducing the full type tag, pysui is not servicing the array (denoted by the comma "," between the two types in the compounded type. I'll get that fixed soon...

**Comment by FrankC01** [comment]
Pushed 0.51.2 to pypi, please upgrade and try again.

**Comment by FrankC01** [comment]
I'm a bit confused. when you say `GetObject` are you refering to the data result itself?

**Comment by FrankC01** [comment]
Merged, thank you for the effort!
