### ISSUE TITLE
String Query Require

### ISSUE THREAD

**Issue by RandyPen** [FrankC01/pysui#202]
I want string query like that
```graphql
query Object {
  object(address:"0xa2e6c7a2160c7744b334ab33b4f6aa992b0a69239414a8c203c77f6303b8ea10") {
    display {
      key 
      value
      error
    }
  }
}
```

**Comment by FrankC01** [comment]
pysui already supports whatever string query you write, see the following [example](https://pysui.readthedocs.io/en/latest/graphql.html#string-queries):
