### ISSUE TITLE
[Question] Add custom header to rpc call

### ISSUE THREAD

**Issue by rony-arnac** [FrankC01/pysui#204]
Hey,

I'd like to add Authorization header to the API call to the RPC endpoint.
How can I add a custom header?

Thanks!

**Comment by FrankC01** [comment]
So:

1. We are sunsetting the JSON RPC api (pysui legacy)
2. We have introduced  GraphQL RPC client (in beta)

So can you confirn  you want the option to be able to do that with every call?

**Comment by rony-arnac** [comment]
Yes I would @FrankC01

**Comment by FrankC01** [comment]
@rony-arnac It went in a few releases ago. You can set at client instantiation as well as each individual 'execute' call.
