### ISSUE TITLE
def sign_message

### ISSUE THREAD

**Issue by crypto-chen** [FrankC01/pysui#233]
keypair = SuiKeyPair()
keypair._private_key = SuiPrivateKey(key_bytes=private_key_bytes, scheme=SignatureScheme.ED25519)

signature = keypair.sign_message('aaa')
print(f"sign: {signature}")

**Comment by crypto-chen** [comment]
thread '<unnamed>' panicked at src\lib.rs:500:40:
called `Result::unwrap()` on an `Err` value: Error decoding aaa
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Traceback (most recent call last):
  File "F:\python240416\re_socl\galxe\草稿.py", line 43, in <module>
    signature = keypair.sign_message('aaa')
  File "E:\Python310\lib\site-packages\pysui\sui\sui_crypto.py", line 125, in sign_message
    return pfc.sign_message(self.scheme, self.private_key.key_bytes, message)
pyo3_runtime.PanicException: called `Result::unwrap()` on an `Err` value: Error decoding aaa

**Comment by crypto-chen** [comment]
This is the signature generated by the wallet: AC8KMNyD9sljktPsGNkCKATjFU8HmQR0dwtPpBETJAjiCZ2VW/vcmNFr6HzRjLJy7v1rbDy15SCxjhtYE2+wAX1cdBnmPJ5buJzjHGxcILHaIJ2TTfA6iqfznUwMieHAA==
This is the signature generated by pysui: vooSJDDsF3L2Zq314gvPCL37RznT5meAycSOXAYx0umRUu7ZAywJf2U1mdIj4iIJVR5UIa1YtuM6wvZRS7nnAQ==
Why are the lengths different?

**Comment by FrankC01** [comment]
Please provide a link to the open source wallet function that produces the signed message, also is the input a base64 encoding of 'aaa' in both cases?

**Comment by crypto-chen** [comment]
![image](https://github.com/user-attachments/assets/4edad17c-0e77-43c0-bef5-1f56b9194806)

This is the base64 string I entered:WW91IGFyZSB1cGRhdGluZyB5b3VyIEdhbHhlIHByb2ZpbGUgd2l0aCBzdWkgYWRkcmVzcyAweDdiYzgzOGUyNTc1NDU5ZWE3NzQzYWFlZDJiNDc3MmU2ZGEzNDYzYTJjYzRmM2I5Njc1MTkyN2E3Y2Y1ZTg5MWIuIFBsZWFzZSBzaWduIHRoZSB0cmFuc2FjdGlvbiB0byBjb25maXJtLgpub25jZTogMTU2ODQxMTEKSXNzdWVkIEF0OiAyMDI0LTEwLTIxVDEyOjE3OjM1LjQwNFoKRXhwaXJhdGlvbiBUaW1lOiAyMDI0LTEwLTI4VDEyOjE3OjM1LjQwNFo=

**Comment by crypto-chen** [comment]
![image](https://github.com/user-attachments/assets/a3d92781-7f61-4dca-8c30-c98dfad28d05)

**Comment by crypto-chen** [comment]
npm i @mysten/sui
It uses the typestrict SDK
![image](https://github.com/user-attachments/assets/8a8aaf7c-69d1-4016-9f10-44be81906cee)

**Comment by FrankC01** [comment]
Refer to this [enhancement](https://github.com/FrankC01/pysui/issues/235)
