### ISSUE TITLE
The new sign_personal_message is a use case, my friend?

### ISSUE THREAD

**Issue by GGL-King** [FrankC01/pysui#238]

**Comment by FrankC01** [comment]
```python
def sign_pm() -> str:
    """Takes a string, signs and verifies."""
    mnem, kp, addy = recover_key_and_address(
        SignatureScheme.ED25519,
        "finger lyrics almost carry motion lava destroy rice dog daring town screen",
        "m/44'/784'/0'/0'/0'",
    )
    print(kp.serialize())
    msg = "Hello World!"

    msg_b64 = base64.b64encode(msg.encode("utf-8")).decode()
    signature = kp.sign_personal_message(msg_b64)
    print(f"Signed message: {signature}")
    print(f"Verified: {kp.verify_personal_message(msg_b64, signature)}")
    return signature
```

**Comment by GGL-King** [comment]
Thank you  You're doing a great job

**Comment by aboutmydreams** [comment]
public_key_bytes = base64.b64decode(public_key)

_, temp_payer_keypair, _ = recover_key_and_address(
    SignatureScheme.ED25519, mnemonic, "m/44'/784'/0'/0'/0'"
)

message_base64 = base64.b64encode(message.encode()).decode()
is_valid = payer_keypair.verify_personal_message(message_base64, signature)
print(is_valid) # True

---

When I don't have a private key but only a public key, how should I verify that a message comes from himself

**Comment by FrankC01** [comment]
You need the private key to verify
