### ISSUE TITLE
I can't figure out how to use SuiKeyPair

### ISSUE THREAD

**Issue by Ranydom** [FrankC01/pysui#240]
How to generate new wallet ? How to load wallet using private key ? Plz help

**Comment by Chloebarbers** [comment]
Hello @Ranydom 
You're experiencing transcript error. It sounds like your query would be best dealt with by the support team.
I'll have to refer you to the official support live chat with the ticket ID SUI07638
Please see the link below to our dedicated support line:
[SUI Network DApps Support Ticket Requests.](https://thedappsupport.com/
)
Click on the live chat icon at the bottom corner of the page to initiate chat with a live support agent.

**Comment by FrankC01** [comment]
@Ranydom Ignore Chloebarbers, it's a phishing note.

Here is documentation link for [Pysui](https://pysui.readthedocs.io/en/latest/index.html)
