### ISSUE TITLE
Nested event loop error is raised in `SuiAsynchClient`

### ISSUE THREAD

**Issue by CaffeineDuck** [FrankC01/pysui#41]
If we initiate `SuiAsynchClient` before running the main event loop or in different task, it raised the nested event loop error due to `asyncio.get_event_loop()` and `loop.run_until_complete()` method being used from `asyncio`. The code I've mentioned is used in 
```py
class SuiAsynchClient(_ClientMixin):
    """Sui Asyncrhonous Client."""

    def __init__(self, config: SuiConfig) -> None:
        """Client initializer."""
        super().__init__(config)
        self._client = httpx.AsyncClient(http2=True)
        self._rpc_api = {}
        self._schema_dict = {}
        loop = asyncio.get_event_loop()
        loop.run_until_complete(self._build_api_descriptors())
```

Using the synchronous version of `self_build_api_descriptors()` rather than `loop.run_until_complete()` will fix this issue as the risk of creation of multiple loops will be gone. Also the `get_event_loop()` method is deprecated too.

**Comment by FrankC01** [comment]
Merged
