### ISSUE TITLE
Can't install req

### ISSUE THREAD

**Issue by Kupperoid** [FrankC01/pysui#5]
<img width="1128" alt="Знімок екрана 2022-10-24 о 23 58 38" src="https://user-images.githubusercontent.com/116599991/197628134-48368e1e-a63e-4bd6-851a-0065f7454b39.png">
<img width="1109" alt="Знімок екрана 2022-10-24 о 23 59 05" src="https://user-images.githubusercontent.com/116599991/197628189-baf5c8b6-cb36-4a9f-ab44-31e882c86245.png">

And a link to pastebin, in case you need it https://pastebin.com/9CsYNr44

I have to tell you right away that I have the SUI binaries installed.
1. I clone from the git to my computer
2. Setup environment
python3 -m venv pysuienv
3. Activate
source pysuienv/bin/activate
4. And try to load packages, but all that happens is that there are errors

**Comment by Kupperoid** [comment]
Sorry for any mistakes, I'm a long way from being a native speaker

**Comment by FrankC01** [comment]
I updated the requirements.txt and added `wheel` which resolves the `secp256k1` error. I did a fresh clone and test and all is well if you can give it another try.

Also updated README.md
