### ISSUE TITLE
how to install in win10 ?

### ISSUE THREAD

**Issue by viponedream** [FrankC01/pysui#70]
how to install in win10 ?

**Comment by FrankC01** [comment]
You would use `pip install pysui` for Python libraries
Also, I strongly recommend using WSL as both Sui binaries and `pysui` will behave better
I have not tested directly on Windows

**Comment by viponedream** [comment]
ubuntu22  vmware
pip install pysui
 src/ed25519-glue/ed25519module.c:17:10: fatal error: Python.h: No such file or directory
