### ISSUE TITLE
expose `_client` in `SuiClient` 

### ISSUE THREAD

**Issue by liuerfire** [FrankC01/pysui#73]
so that we can custom requests, e.g. making a batch request, like the official TS sdk https://github.com/MystenLabs/sui/blob/0.6.5-release/sdk/typescript/src/rpc/client.ts#L123

**Comment by FrankC01** [comment]
No need, there is a Batch builder unless you mean something else.

**Comment by liuerfire** [comment]
Oh, I didn't notice that `SuiArray` exists. Thanks!
