### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by mazepas** [FrankC01/pysui#86]
Hi, cannot install pysui
```
pip install pysui
Collecting pysui
  Using cached pysui-0.15.0-py3-none-any.whl (125 kB)
Collecting dataclasses-json==0.5.7
  Using cached dataclasses_json-0.5.7-py3-none-any.whl (25 kB)
Collecting pyyaml==6.0
  Using cached PyYAML-6.0-cp311-cp311-win_amd64.whl (143 kB)
Collecting secp256k1==0.14.0
  Using cached secp256k1-0.14.0.tar.gz (2.4 MB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [1 lines of output]
      'pkg-config' is required to install this package. Please see the README for details.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

```
pip list
Package             Version
aiohttp             3.8.4
aiosignal           1.3.1
asn1crypto          1.5.1
async-timeout       4.0.2
attrs               22.2.0
base58              2.1.1
beautifulsoup4      4.12.1
bip-utils           2.7.0
bitarray            2.7.3
bs4                 0.0.1
cbor2               5.4.6
certifi             2022.12.7
cffi                1.15.1
charset-normalizer  3.1.0
cloudscraper        1.2.69
coincurve           17.0.0
colorama            0.4.6
cprint              1.2.2
crcmod              1.7
cytoolz             0.12.1
ecdsa               0.18.0
ed25519-blake2b     1.4
eth-abi             4.0.0
eth-account         0.8.0
eth-hash            0.5.1
eth-keyfile         0.6.1
eth-keys            0.4.0
eth-rlp             0.3.0
eth-typing          3.3.0
eth-utils           2.1.0
ez-setup            0.9
fake-useragent      1.1.3
frozenlist          1.3.3
hdwallet            2.2.1
hexbytes            0.3.0
idna                3.4
ipfshttpclient      0.8.0a2
jsonschema          4.17.3
loguru              0.6.0
lru-dict            1.1.8
lxml                4.9.2
mnemonic            0.20
multiaddr           0.0.9
multidict           6.0.4
netaddr             0.8.0
parsimonious        0.9.0
pip                 23.0.1
pretty              0.1
protobuf            4.22.1
py-sr25519-bindings 0.2.0
pycparser           2.21
pycryptodome        3.17
pykg-config         1.3.0
PyNaCl              1.5.0
pyparsing           3.0.9
pyrsistent          0.19.3
pysdk-sui           5.1
pyuseragents        1.0.5
pywin32             306
regex               2023.3.23
requests            2.28.2
requests-toolbelt   0.10.1
rlp                 3.0.0
setuptools          67.6.1
six                 1.16.0
soupsieve           2.4
sui                 0.1.13
termcolor           2.2.0
toolz               0.12.0
urllib3             1.26.15
utils               1.0.1
varint              1.0.2
web3                6.0.0
websockets          11.0
wheel               0.40.0
win32-setctime      1.1.0
yarl                1.8.2
```
Have can I resolve this problem?

**Comment by FrankC01** [comment]
Can you try `pip install --use-pep517 -r requirements.txt`

**Comment by FrankC01** [comment]
@mazepas Did that fix the install for you?

**Comment by Crawlling** [comment]
> @mazepas Did that fix the install for you?

Sir, I got same problem: when i install pysui till pysui_fastcrypto, then i got this:

Preparing metadata (pyproject.toml) ... error
error: subprocess-exited-with-error

  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [20 lines of output]
      Checking for Rust toolchain....
      Running `maturin pep517 write-dist-info --metadata-directory /tmp/pip-modern-metadata-2n24uxk8 --interpreter /usr/bin/python3`
      Traceback (most recent call last):
        File "/usr/lib/python3/dist-packages/pip/_vendor/pep517/in_process/_in_process.py", line 363, in <module>
          main()
        File "/usr/lib/python3/dist-packages/pip/_vendor/pep517/in_process/_in_process.py", line 345, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/usr/lib/python3/dist-packages/pip/_vendor/pep517/in_process/_in_process.py", line 164, in prepare_metadata_for_build_wheel
          return hook(metadata_directory, config_settings)
        File "/tmp/pip-build-env-s6xd04t7/overlay/local/lib/python3.10/dist-packages/maturin/__init__.py", line 192, in prepare_metadata_for_build_wheel
          _output = subprocess.check_output(command)
        File "/usr/lib/python3.10/subprocess.py", line 421, in check_output
          return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
        File "/usr/lib/python3.10/subprocess.py", line 503, in run
          with Popen(*popenargs, **kwargs) as process:
        File "/usr/lib/python3.10/subprocess.py", line 971, in __init__
          self._execute_child(args, executable, preexec_fn, close_fds,
        File "/usr/lib/python3.10/subprocess.py", line 1863, in _execute_child
          raise child_exception_type(errno_num, err_msg, err_filename)
      FileNotFoundError: [Errno 2] No such file or directory: 'maturin'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

already install sui and rustup, thx sir.
